# ---------- Build stage ----------
    FROM maven:3.9.6-eclipse-temurin-21 AS build

    WORKDIR /app
    
    COPY pom.xml .
    RUN mvn dependency:go-offline -B
    
    COPY src ./src
    
    RUN mvn clean package -DskipTests
    
    
    # ---------- Runtime stage ----------
    FROM eclipse-temurin:21-jdk-alpine
    
    WORKDIR /app
    
    COPY --from=build /app/target/*.jar app.jar
    
    ENV PORT=8080
    
    EXPOSE 8080
    
    ENTRYPOINT ["sh", "-c", "java -jar app.jar --server.port=$PORT"]